### ISSUE TITLE
ctags installation failed

### ISSUE THREAD

**Issue by schneiderpy** [ropensci-review-tools/pkgstats#63]
I have downloaded the `pkgstats` pkg, which indicates that `ctags` is automatically installed on Windows, however, it seems that this has failed (on Windows 10/11), since I received the following error:

`Error: package or namespace load failed for ‘pkgstats’:
 .onAttach failed in attachNamespace() for 'pkgstats', details:
  call: NULL
  error: No ctags installation found.`

**Comment by mpadge** [comment]
{pkgstats} was prevented by CRAN from automatically installing ctags (for good reason), so hasn't had that message for quite some time. If you've got the latest version installed, you should see this message the first time you load it:
> This package requires downloading and installing binary 'universal-ctags' software from https://github.com/rwinlib/universal-ctags/. Do you agree (y/n)?"

Alternatively, run `pkgstats:::install_ctags_windows()` - note the three `:::`, because it's an internal (non-exported) function. If the latter says no such function, then your version of this package is out of date.
